payment: fix java.sql.SQLDataException in PendingTransactionTask
This fixes:

  java.sql.SQLDataException: Data too long for column 'updated_by' at row 1

as updated_by was set to org.killbill.billing.payment.core.janitor.PendingTransactionTask,
which is longer than the updated_by column.

Signed-off-by: Pierre-Alexandre Meyer <pierre@mouraf.org>