payment: add toString() method to payment exceptions
The exception message field is null - we were printing useless messages
in the logs such as:

om.ning.billing.payment.api.PaymentApiException: Failed to create payment for account d78882c8-8622-4380-81c0-0e363d3910c9 : null

Signed-off-by: Pierre-Alexandre Meyer <pierre@ning.com>